apiVersion: apps/v1
kind: Deployment
metadata:
  name: apphone
spec:
  replicas: 30
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 463117628373.dkr.ecr.us-east-1.amazonaws.com/mahi:latest
          ports:
            - containerPort: 80
