apiVersion: apps/v1
kind: Deployment
metadata:
  name: apphone
spec:
  replicas: 30
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: pandev.azurecr.io/pandev:latest
          ports:
            - containerPort: 80
